name: Build and Test Pipeline

#on:
 # push:
  #  branches: [ "main" ]
 # pull_request:
  #  branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Project
      working-directory: backend
      run: |
        chmod +x gradlew
        ./gradlew clean bootJar

    - name: Specify Docker image
      run: echo "Dockerfile is already specified in the core task"

    - name: Run Docker image with PostgreSQL dependency
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Execute static testing (Sonar)
      run: |
        cd backend
        ./gradlew sonarqube

    - name: Execute dynamic testing (unit)
      run: |
        cd backend
        ./gradlew test --tests [Referenz zu Unit Tests]

        

